apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  labels:
    app: echo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo-app
        image: pshemassazurek8acr.azurecr.io/zio-keeper-examples:0.1.4
        ports:
        - containerPort: 5558
---
apiVersion: v1
kind: Service
metadata:
  name: echo-srv
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: echo-app
  ports:
  - name: zio-keeper
    port: 5558