apiVersion: 1
persistence:
  enabled: true
  accessModes: {ReadWriteOnce}
  size: 8Gi
datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-server
    access: proxy
    isDefault: true
